/** Display phrases for company cards. Source data stays Chinese. */
export const COMPANY_PHRASES: [string, string][] = [
  ["Yahoo 2026-10-08 现价；市值与市盈率 Screener.in 同日，市值 ₹592244 Cr 按美元兑卢比 96.77 折算", "Yahoo price on 2026-10-08; market cap and P/E from Screener.in the same day; market cap ₹592244 Cr converted at USD/INR 96.77"],
  ["上市信贷公司，当地牌照未在这张卡上核过", "listed credit company; the local license is not checked on this card"],
  ["，集团海外合计，未拆到本国", "; group overseas total, not split to this country"],
  ["，集团披露，未拆到本国", "; group disclosure, not split to this country"],
  ["支付，名录写了信贷产品", "payments; the roster lists a credit product"],
  ["商店应用，牌照未核", "store app, license not checked"],
  ["信用飞（国内）；出海本地化平台（公开产品名待核实）", "CreditFly (domestic); localized overseas platforms (public product names not verified)"],
  ["孟加拉 MFS 头筹（银行关联）", "Bangladesh MFS leader (bank-linked)"],
  ["BOT 非银个人贷/Nano（非 Virtual Bank）", "BOT non-bank personal loans / Nano (not a virtual bank)"],
  ["阿根廷数字银行路径；墨申牌", "Argentina digital-bank path; Mexico license application"],
  ["电商金融；MX/BR 信贷臂", "e-commerce finance; MX/BR credit arms"],
  ["拉美数字银行；MX 信贷/账户扩张", "LatAm digital bank; MX credit and account expansion"],
  ["互联网银行；出海TH/ID", "internet bank; overseas in TH/ID"],
  ["哥伦比亚钱包；走向独立牌照叙事", "Colombia wallet; moving toward its own license"],
  ["科技型银行；GoTo 资金伙伴", "tech bank; GoTo funding partner"],
  ["支付机构→数字银行叙事", "payments firm moving toward a digital-bank story"],
  ["数字零售银行牌照叙事", "digital retail-bank license story"],
  ["BSP 数字银行 / PDIC 投保", "BSP digital bank / PDIC-insured"],
  ["BSP数字银行/PDIC投保", "BSP digital bank / PDIC-insured"],
  ["新贷逾期（年末）", "new-loan delinquency (year-end)"],
  ["促成+自营放款量", "facilitated plus own-book originations"],
  ["嘉银系；出海品牌含Soluskita等历史线", "Jiayin group; overseas brands include historical lines such as Soluskita"],
  ["国内多品牌；印尼AdaKami；菲JuanHand；澳Fundo", "several domestic brands; Indonesia AdaKami; Philippines JuanHand; Australia Fundo"],
  ["SUPEREV；与芝麻/乐道等联名订阅", "SUPEREV; co-branded subscriptions with Sesame and Ledao"],
  ["洋钱罐；印尼Easycash；墨Credmex", "Yangqianguan; Indonesia Easycash; Mexico Credmex"],
  ["Surfin；印尼Ayovest等扩展产品", "Surfin; expansion products in Indonesia such as Ayovest"],
  ["JazzCash（Android/iOS借贷工具）", "JazzCash (Android/iOS lending tool)"],
  ["分期乐（现以信贷服务为主）", "Fenqile (now mainly a credit service)"],
  ["虚拟银行消费/信贷产品", "virtual-bank consumer and credit products"],
  ["Fuliza/M-Shwari 等合作贷", "partner loans such as Fuliza / M-Shwari"],
  ["ReadyCash 大规模数字贷", "ReadyCash large-scale digital loans"],
  ["全栈数字银行信贷", "full-stack digital-bank credit"],
  ["弱于四强信贷臂", "weaker than the four leading credit arms"],
  ["现金贷/设备贷/BNPL", "cash loan / device loan / BNPL"],
  ["Payments Bank/PPI 路径", "payments-bank / PPI path"],
  ["HKMA 虚拟银行牌照", "HKMA virtual-bank license"],
  ["支付+P2P+多金融+BNC", "payments + P2P + multi-finance + BNC"],
  ["支付入口信贷导流", "credit referrals from the payments entry"],
  ["阿根廷/区域钱包+卡", "Argentina / regional wallet and card"],
  ["Banxico SPEI；CoDi/DiMo 服务层", "Banxico SPEI; CoDi/DiMo service layer"],
  ["EMI/数字银行交叉", "EMI / digital-bank overlap"],
  ["MAS 数字银行路径", "MAS digital-bank path"],
  ["MX 收单/支付机构路径", "MX acquiring / payments-institution path"],
  ["MX 线上商户/SME 信贷", "MX online merchant / SME credit"],
  ["Paytm 信贷/保险交叉", "Paytm credit and insurance cross-sell"],
  ["个贷/分销+NBFC", "personal loans / distribution + NBFC"],
  ["公司 6-K/新闻稿", "company 6-K / press release"],
  ["公司 8-K / IR", "company 8-K / IR"],
  ["城市个人贷 AUM", "urban personal-loan AUM"],
  ["贷款利息与费用", "loan interest and fees"],
  ["国内 90+ 逾期", "domestic 90+ past due"],
  ["累计注册用户", "cumulative registered users"],
  ["金融分部收入", "financial-segment revenue"],
  ["金融 Adj. EBITDA", "financial Adj. EBITDA"],
  ["分期电商 GMV", "installment e-commerce GMV"],
  ["1–30 天逾期", "1–30 day past due"],
  ["61–90 天逾期", "61–90 day past due"],
  ["90+ 逾期率", "90+ delinquency rate"],
  ["BSP 数字银行 / PDIC", "BSP digital bank / PDIC"],
  ["BCA 数字银行", "BCA digital bank"],
  ["BCI 数字钱包", "BCI digital wallet"],
  ["BCP 系国民级钱包", "BCP national wallet"],
  ["BNPL/信用卡路径", "BNPL / credit-card path"],
  ["CMF 银行牌照", "CMF bank license"],
  ["HKMA虚拟银行", "HKMA virtual bank"],
  ["ID PDKB 数字银行", "ID PDKB digital bank"],
  ["LINE 生态信贷导流", "LINE ecosystem credit referrals"],
  ["Maybank 超级App", "Maybank super-app"],
  ["NPCI 即时支付", "NPCI instant payments"],
  ["PJP 等支付牌照簇", "PJP and related payments licenses"],
  ["SME 线上贷", "SME online lending"],
  ["Akulaku 银行臂叙事", "Akulaku bank-arm story"],
  ["Banxico手机号转账", "Banxico phone-number transfer"],
  ["ID 电子货币", "ID e-money"],
  ["LPBBTI 微贷", "LPBBTI microloan"],
  ["MX 线上消费贷", "MX online consumer loan"],
  ["MY 电子货币", "MY e-money"],
  ["TH 电子货币", "TH e-money"],
  ["VN 电子钱包", "VN e-wallet"],
  ["东非零售行", "East Africa retail bank"],
  ["保险系数字银行", "insurer-backed digital bank"],
  ["南非数字银行", "South Africa digital bank"],
  ["即时支付公共层", "instant-payments public layer"],
  ["商户 UPI/POS", "merchant UPI / POS"],
  ["商户收单/代理银行", "merchant acquiring / agent banking"],
  ["国有系钱包", "state-linked wallet"],
  ["埃及 BNPL/分期", "Egypt BNPL / installments"],
  ["多国消费金融", "multi-country consumer finance"],
  ["多国牌照拼图", "multi-country license patchwork"],
  ["多国移动货币", "multi-country mobile money"],
  ["大众银行头筹", "Public Bank lead"],
  ["大型 NBFC", "large NBFC"],
  ["大行+数字臂", "large bank plus digital arm"],
  ["孟加拉 MFS 第二", "Bangladesh MFS number two"],
  ["巴西数字银行标杆", "Brazil digital-bank benchmark"],
  ["担保消费贷", "guaranteed consumer loan"],
  ["持牌消金", "licensed consumer finance"],
  ["挑战者银行", "challenger bank"],
  ["支付+信贷导流", "payments plus credit referrals"],
  ["数字卡/信贷", "digital card / credit"],
  ["数字贷/银行路径", "digital lending / bank path"],
  ["数字银行/车贷", "digital bank / auto loan"],
  ["无网点数字银行", "branchless digital bank"],
  ["电信+Payments Bank", "telco plus payments bank"],
  ["电信系数字银行", "telco digital bank"],
  ["电商（Kaspi）", "e-commerce (Kaspi)"],
  ["私行+Cake母行", "private bank plus Cake parent"],
  ["线上现金贷头部样本", "leading online cash-loan sample"],
  ["线上短贷/BNPL", "short online loans / BNPL"],
  ["肯尼亚移动货币标杆", "Kenya mobile-money benchmark"],
  ["西非低费率钱包", "West Africa low-fee wallet"],
  ["超级应用+银行金融", "super-app plus bank finance"],
  ["超级应用嵌入金融", "finance embedded in a super-app"],
  ["重整银行数字品牌", "restructured bank's digital brand"],
  ["银联入口", "UnionPay entry"],
  ["银行系钱包", "bank-owned wallet"],
  ["银行联盟支付", "bank-consortium payments"],
  ["银行联盟钱包", "bank-consortium wallet"],
  ["马来数字银行", "Malaysia digital bank"],
  ["高端信用卡用户", "premium credit-card users"],
  ["BankTech/合作贷", "BankTech / partner loans"],
  ["BNPL/商户贷", "BNPL / merchant loans"],
  ["BNPL/现金贷", "BNPL / cash loan"],
  ["BNPL/贷/存款", "BNPL / loans / deposits"],
  ["GLoan 等", "GLoan and others"],
  ["OKash/信贷", "OKash / credit"],
  ["Paytm 信贷/保险交叉", "Paytm credit and insurance cross-sell"],
  ["ZIP/信贷", "ZIP / credit"],
  ["个贷/小微", "personal and micro loans"],
  ["侨汇/数字银行", "remittances / digital bank"],
  ["信用卡/个贷", "credit card / personal loan"],
  ["信用卡/信贷", "credit card / credit"],
  ["信贷/分期派生", "credit and installment products off the wallet"],
  ["信贷/投资入口", "credit and investment entry"],
  ["信贷合作导流", "credit-partnership referrals"],
  ["借贷/保险派生", "lending and insurance products"],
  ["分付等路径", "Fenfu and similar paths"],
  ["卡/个贷", "card / personal loan"],
  ["卡/消费贷", "card / consumer loan"],
  ["合作纳米贷", "partner nano loans"],
  ["吸储/小额贷", "deposits / small loans"],
  ["商户/消费信贷", "merchant / consumer credit"],
  ["商户贷/BNPL", "merchant loans / BNPL"],
  ["商户贷/分期", "merchant loans / installments"],
  ["商户贷产品", "merchant-loan products"],
  ["存款/贷经母行", "deposits and loans via the parent bank"],
  ["存款+中长期贷", "deposits plus medium- and long-term loans"],
  ["小额贷派生", "small-loan products"],
  ["微粒贷等", "Weilidai and similar"],
  ["数字信贷扩容", "digital-credit expansion"],
  ["数字银行放贷", "digital-bank lending"],
  ["有钱花等", "Youqianhua and similar"],
  ["消费/商户信贷", "consumer / merchant credit"],
  ["消费贷/EMI", "consumer loan / EMI"],
  ["消费贷/卡", "consumer loan / card"],
  ["现金贷 P2P", "cash-loan P2P"],
  ["现金贷/设备贷", "cash loan / device loan"],
  ["现金贷/分期", "cash loan / installments"],
  ["生态嵌入放贷", "lending embedded in the ecosystem"],
  ["花呗借呗路径", "Huabei and Jiebei path"],
  ["车房抵押贷", "auto and home secured loans"],
  ["车贷/个贷", "auto loan / personal loan"],
  ["透支/储蓄贷", "overdraft / savings-backed loan"],
  ["金融导入中", "finance still being rolled in"],
  ["钱包信贷派生", "credit products off the wallet"],
  ["银行信贷导流", "bank credit referrals"],
  ["长短期分期", "short- and long-term installments"],
  ["零售/消费信贷", "retail / consumer credit"],
  ["高频率小额贷", "high-frequency small loans"],
  ["JiuJiu / 久久租机", "JiuJiu / Jiujiu device rental"],
  ["印尼Doeku（收购）", "Indonesia Doeku (acquired)"],
  ["公司新闻稿/IR", "company press release / IR"],
  ["全年业绩公告", "full-year results announcement"],
  ["业绩新闻/IR", "earnings news / IR"],
  ["母行数字臂", "parent bank's digital arm"],
  ["大行数字臂", "large bank's digital arm"],
  ["央行即时支付", "central-bank instant payments"],
  ["即时支付", "instant payments"],
  ["电信钱包", "telco wallet"],
  ["互联网银行", "internet bank"],
  ["互联网信贷", "internet credit"],
  ["在位大行", "incumbent large bank"],
  ["在位私行", "incumbent private bank"],
  ["在位公行", "incumbent state bank"],
  ["超级应用金融", "super-app finance"],
  ["数字银行/卡", "digital bank / card"],
  ["数字银行贷", "digital-bank loans"],
  ["数字银行信贷", "digital-bank credit"],
  ["数字钱包", "digital wallet"],
  ["数字账户", "digital account"],
  ["数字贷", "digital lending"],
  ["消费分期", "installment credit"],
  ["消费金融", "consumer finance"],
  ["消费贷", "consumer loan"],
  ["现金贷", "cash loan"],
  ["闭环BNPL", "closed-loop BNPL"],
  ["电商BNPL", "e-commerce BNPL"],
  ["电商金融", "e-commerce finance"],
  ["电商钱包", "e-commerce wallet"],
  ["电子钱包", "e-wallet"],
  ["移动货币信贷", "mobile-money credit"],
  ["资金移动/支付", "money movement / payments"],
  ["跨境/钱包", "cross-border / wallet"],
  ["钱包+信贷", "wallet plus credit"],
  ["钱包内信贷", "in-wallet credit"],
  ["零售分期", "retail installments"],
  ["非洲收单", "Africa acquiring"],
  ["全球收单", "global acquiring"],
  ["全球钱包", "global wallet"],
  ["公行超级App", "state-bank super-app"],
  ["统一QR", "unified QR"],
  ["收单", "acquiring"],
  ["新银行", "new bank"],
  ["纯网银", "online-only bank"],
  ["虚拟银行", "virtual bank"],
  ["数字银行", "digital bank"],
  ["本地银行", "local bank"],
  ["支付+导流", "payments plus referrals"],
  ["支付+银行", "payments plus bank"],
  ["EMI/钱包", "EMI / wallet"],
  ["SME/商户贷", "SME / merchant loans"],
  ["BNPL/卡", "BNPL / card"],
  ["BNPL/分期", "BNPL / installments"],
  ["场景信贷导流", "scene-based credit referrals"],
  ["零售/SME", "retail / SME"],
  ["零售/卡", "retail / card"],
  ["零售/消金", "retail / consumer finance"],
  ["账户/卡", "account / card"],
  ["账户/贷", "account / loan"],
  ["卡/贷", "card / loan"],
  ["卡/支付", "card / payments"],
  ["个贷", "personal loan"],
  ["线上贷", "online lending"],
  ["零售贷", "retail loans"],
  ["小微贷", "micro and small-business loans"],
  ["小额贷", "small loans"],
  ["店内贷", "in-store loans"],
  ["社区贷", "community loans"],
  ["经营贷", "business loans"],
  ["行内贷", "in-bank loans"],
  ["钱包贷", "wallet loans"],
  ["合作信贷", "partner credit"],
  ["信贷合作", "credit partnership"],
  ["借贷合作", "lending partnership"],
  ["信贷导流", "credit referrals"],
  ["信贷派生", "derived credit products"],
  ["支付派生", "derived payments products"],
  ["交叉销售", "cross-sell"],
  ["银行客群", "bank customers"],
  ["视市场", "depends on the market"],
  ["金融租赁", "financial leasing"],
  ["汽车金融", "auto finance"],
  ["信用租赁", "credit lease"],
  ["促成成交量", "facilitated volume"],
  ["贷款应收", "loan receivables"],
  ["30+ 逾期", "30+ past due"],
  ["90+ 逾期", "90+ past due"],
  ["放款量", "origination volume"],
  ["在贷本金", "outstanding principal"],
  ["总成交量", "total volume"],
  ["国内成交量", "domestic volume"],
  ["海外成交量", "overseas volume"],
  ["海外在贷", "overseas outstanding"],
  ["内地放款量", "mainland originations"],
  ["在贷余额", "outstanding balance"],
  ["Day-1 逾期", "Day-1 past due"],
  ["总收入", "total revenue"],
  ["净收入", "net revenue"],
  ["净利", "net profit"],
  ["季放款额", "quarterly originations"],
  ["总贷款组合", "total loan portfolio"],
  ["信贷组合", "credit portfolio"],
  ["无抵押贷", "unsecured loans"],
  ["墨西哥客户", "Mexico customers"],
  ["总放款额", "total originations"],
  ["个人贷放款", "personal-loan originations"],
  ["学贷放款", "student-loan originations"],
  ["房贷放款", "mortgage originations"],
  ["笔均", "average ticket"],
  ["公司新闻稿", "company press release"],
  ["公司业绩稿", "company earnings release"],
  ["公司 IR", "company IR"],
  ["公司 6-K", "company 6-K"],
  ["Watu Simu 等", "Watu Simu and others"],
  ["快牛 / KN / MexiCash", "Kuainiu / KN / MexiCash"],
  ["易鑫 / Yixin", "Yixin"],
  ["BNPL合作", "BNPL partnership"],
  ["奇富借条", "Qifu Jietiao"],
  ["消费分期 BNPL（Lazada/TikTok白标）", "installment credit BNPL (Lazada/TikTok white-label)"],
  ["个人借款-个人现金贷", "personal borrowing - personal cash loan"],
  ["个人现金贷(P2P大盘)", "personal cash loan (P2P book)"],
  ["香港虚拟银行集群（ZA/Mox/livi/Welab 等）", "Hong Kong virtual-bank cluster (ZA, Mox, livi, Welab, and others)"],
  ["SPEI / CoDi / DiMo 通道", "SPEI / CoDi / DiMo rail"],
  ["Synchrony苹果包", "Synchrony Apple package"],
  ["Home Credit设备贷", "Home Credit device loans"],
  ["Mercado Credito分期", "Mercado Credito installments"],
  ["PayPal欧盟分期", "PayPal EU installments"],
  ["Samsung巴西金融", "Samsung Brazil finance"],
  ["GXS / GXBank（Grab 系）", "GXS / GXBank (Grab group)"],
  ["Nubank（含墨西哥）", "Nubank (including Mexico)"],
  ["Jumia Pay分期", "Jumia Pay installments"],
  ["Akulaku X（泰）", "Akulaku X (Thailand)"],
  ["LINE Bank 台湾", "LINE Bank Taiwan"],
  ["Bandusaku（对外清单名）", "Bandusaku (name on the external list)"],
  ["快牛 / KN / MexiCash", "Kuainiu / KN / MexiCash"],
  ["AEON Thana（泰消费金融）", "AEON Thana (Thailand consumer finance)"],
  ["Nu Holdings（B3 存托）", "Nu Holdings (B3 depositary receipts)"],
  ["嘉银 Jiayin / Samir", "Jiayin / Samir"],
  ["腾讯控股", "Tencent Holdings"],
  ["微众科技", "WeBank Technology"],
  ["蚂蚁集团", "Ant Group"],
  ["泰消费金融", "Thailand consumer finance"],
  ["嘉银系", "Jiayin group"],
  ["有钱花", "Youqianhua"],
  ["江苏法巴农科设备金租", "Jiangsu BNP Paribas agricultural-equipment leasing"],
  ["斯泰兰蒂斯汽金", "Stellantis Auto Finance"],
  ["平安租赁消费臂", "Ping An leasing, consumer arm"],
  ["小赢科技", "X Financial"],
  ["小赢卡贷", "Xiaoying card loan"],
  ["海尔消金", "Haier Consumer Finance"],
  ["哈银消金", "Harbin Bank Consumer Finance"],
  ["宝马汽金", "BMW Auto Finance"],
  ["北汽汽金", "BAIC Auto Finance"],
  ["陆金所", "Lufax"],
  ["宜人", "Yiren Digital"],
  ["易鑫", "Yixin"],
  ["小赢", "Xiaoying"],
  ["与芝麻", "Sesame"],
  ["趣店", "Qudian"],
  ["印闪", "Adapundi"],
  ["百度", "Baidu"],
  ["存托", "depositary receipts"],
  ["监管", "supervisor"],
  ["维信 Vcredit", "Vcredit"],
  ["蚂蚁消金", "Ant consumer finance"],
  ["京东消金", "JD consumer finance"],
  ["平安消金", "Ping An consumer finance"],
  ["维信金科", "VCREDIT"],
  ["小米消金", "Xiaomi consumer finance"],
  ["招联消金", "Zhaolian consumer finance"],
  ["Coppel分期", "Coppel installments"],
  ["个人现金贷", "personal cash loan"],
  ["底层运营", "operating company"],
  ["借款/SPV", "borrower / SPV"],
  ["对外清单名", "name on the external list"],
  ["集团Holdco", "group holdco"],
  ["印度放贷", "India lending"],
  ["墨西哥现金贷", "Mexico cash loan"],
  ["嘉银集团", "Jiayin group"],
  ["蓝色光标", "BlueFocus"],
  ["乐天银行", "Rakuten Bank"],
  ["微众银行", "WeBank"],
  ["网商银行", "MYbank"],
  ["转数快 FPS", "FPS"],
  ["云闪付", "UnionPay QuickPass"],
  ["微信支付", "WeChat Pay"],
  ["Maya 信贷", "Maya credit"],
  ["携程拿去花", "Trip.com Naquhua"],
  ["苏宁任性付", "Suning Renxingfu"],
  ["消费信贷", "consumer credit"],
  ["信用飞", "CreditFly"],
  ["洋钱罐", "Yangqianguan"],
  ["阿卡拉克", "Akulaku"],
  ["美卡多", "Mercado Libre"],
  ["度小满", "Du Xiaoman"],
  ["支付宝", "Alipay"],
  ["分期乐", "Fenqile"],
  ["代理商", "agent"],
  ["贸易名", "trade name"],
  ["白标", "white-label"],
  ["快牛", "Kuainiu"],
  ["滴滴", "DiDi"],
  ["维信", "Vcredit"],
  ["乐信", "Lexin"],
  ["奇富", "Qifu"],
  ["京东", "JD"],
  ["美团", "Meituan"],
  ["抖音", "Douyin"],
  ["蚂蚁", "Ant"],
  ["腾讯", "Tencent"],
  ["信也", "Xinyi"],
  ["嘉银", "Jiayin"],
  ["亏损", "loss"],
  ["收购", "acquired"],
  ["国内", "domestic"],
  ["也称", "also called"],
  ["放贷主体", "lender"],
  ["优先名单", "priority list"],
  ["市盈率", "P/E"],
  ["无报价", "no quote"],
  ["市值", "market cap"],
  ["同比", "yoy"],
  ["行情", "quote"],
  ["财报", "filing"],
  ["已投", "invested"],
  ["消金", "consumer finance"],
  ["钱包", "wallet"],
  ["支付", "payments"],
  ["收单", "acquiring"],
  ["零售", "retail"],
  ["分期", "installments"],
  ["账户", "account"],
  ["合作", "partnership"],
  ["信贷", "credit"],
  ["借贷", "lending"],
  ["导流", "referrals"],
  ["吸储", "deposits"],
  ["后付", "pay later"],
  ["弱", "thin"],
  ["本基金投资", "this fund invested"],
];
